services:
  ui:
    image: ui:{{short_sha}}
    command: sh -c "npx serve out"
    networks:
      - traefik-net
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager ]
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.app.entrypoints=https"
        - "traefik.http.routers.app.rule=Host(`willz.dev`)"
        - "traefik.http.routers.app.tls=true"
        - "traefik.http.routers.app.tls.certresolver=base_resolver"
        - "traefik.http.routers.app.service=app"
        - "traefik.http.services.app.loadbalancer.server.port=3000"
        -
networks:
  traefik-net:
    external: true