import {Inter} from "next/font/google";
import "./globals.css";
import {Toaster} from "@/components/ui/toaster";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en" style={{colorScheme: 'dark'}} className="h-full dark">
        <head>
            <title>Willz</title>
        </head>

        <body className={inter.className + '  overflow-x-hidden'}>
        {children}
        <Toaster />
        <footer className="w-full h-[70px] flex justify-center items-center flex-col">
            <span>
            Made with ❤️ by&nbsp;<a href="https://github.com/FernandesWilliam" className="text-primary"
                                    target="_blank">Will</a>
                </span>
            <span className={'text-[10px] text-gray-300'}>Updated 15 August of 2024</span>
        </footer>
        </body>

        </html>
    );
}
